#!/usr/bin/env bash

set -e

export CURR_DIR=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)
source "${CURR_DIR}/prepare_env"

# Removes all downloaded files and build artifacts

rm -rf \
"${ARCHIVE_NAME}" \
"${TMP_DIR}" \
"${NODE_DIR}" \
"${CURR_DIR}/../node_modules" \
"${CURR_DIR}/../.build" \
"${CURR_DIR}/../package-lock.json" \
"${CURR_DIR}/../yarn-error.log" \
"${CURR_DIR}/../yarn.lock" \
