#!/usr/bin/env bash

set -e

export CURR_DIR=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)


# Prepares shell environment for building/running the app

export TMP_DIR="${CURR_DIR}/../.tmp"
export NODE_DIR="${CURR_DIR}/../node"
export PATH="${NODE_DIR}/bin:${CURR_DIR}/../node_modules/.bin${PATH:+:$PATH}"
