#!/usr/bin/env bash
set -e

# Creates a local python virtual environment and installs the dependencies
# Required for the project.

# Assumes Python 3 interpreter and pip and virtualenv packages are installed
# and are ready-availible.

PROJECT_NAME=bc

virtualenv --python=python3 ${PROJECT_NAME}
source ${PROJECT_NAME}/bin/activate
python -m pip install --upgrade pip
python -m pip install --upgrade -r requirements.txt
