#!/usr/bin/env bash
set -e

# Prepares shell environment for running the apps

export CURR_DIR=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)

export PROJECT_ROOT="$(dirname ${CURR_DIR})"
export TMP_DIR="${PROJECT_ROOT}/.tmp"
export CONDA_DIR="${PROJECT_ROOT}/.conda"
export VIRTUALENV_DIR="${PROJECT_ROOT}/.${PROJECT_NAME}"

# Activate virtual environment
if [ -f "${VIRTUALENV_DIR}/bin/activate" ]; then
    source "${VIRTUALENV_DIR}/bin/activate"
fi

# Add current dir to python module search path
export PYTHONPATH=${CURR_DIR}/../${PYTHONPATH:+:PYTHONPATH}
